twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        cart_service: '@App\Service\CartService'
        cats: '@App\Twig\CatsExtension'

when@test:
    twig:
        strict_variables: true
